# Generated by Django 5.0.3 on 2024-03-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_published_blog_views_count_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
    ]
