# Generated by Django 4.2 on 2024-04-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_product', 'Can edit product'), ('can_edit_description', 'Can edit description'), ('can_edit_is_published', 'Can edit is_published')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
